### ISSUE TITLE
recursion problem when adding a link field

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/headless#12]
Whenever you add a link field in the view, the api returns no json. The problem is that the link field generates a recursion in the array that json cannot cope with.

To reproduce this: create a content type, add a link field, create a view which list that content type, add title and link fields. Go to the api url, you get a blank page. To test the error, paste `echo json_last_error_msg()` in the `headless_views($views)` function:

```
/**
 * Page callback for views.
 */
function headless_views($view) {
  $config = config_get('headless.settings', 'views');
  if ($config[$view] != 1) {
    $json_error = ['code' => 404];
    backdrop_json_output($json_error);
    backdrop_exit();
  }
  $results = views_get_view_result($view);
  $count = count($results);
  $my_json = [
    'results' => $results,
    'count' => $count,
  ];
  backdrop_json_output($my_json);
  echo json_last_error_msg(); //<--------- paste it here
  backdrop_exit();
}
```

This seems to be more of a problem of the way backdrop is building the $view array which contains a link field than a problem with headless module. My work arround is using just a plain text to insert a link instead of using a link field.

**Comment by robertgarrigos** [comment]
found the problem and filed a PR for backdrop (https://github.com/backdrop/backdrop/pull/2792)
The problem was reported and fixed in drupal here: https://www.drupal.org/project/link/issues/2295071

**Comment by serundeputy** [comment]
thanks @robertgarrigos you are amazing!

**Comment by robertgarrigos** [comment]
Thank you! This module is awesome!!

**Comment by serundeputy** [comment]
I see the PR; did you file a corresponding core issue? if not perhaps copy this issue over to core

**Comment by robertgarrigos** [comment]
nop, I didn't. Just referenced to this.

**Comment by robertgarrigos** [comment]
Done

https://github.com/backdrop/backdrop-issues/issues/3934

**Comment by olafgrabienski** [comment]
IIRC, #3934 has been fixed, so can we close this one?

@robertgarrigos I'm asking myself if this issue is about the same problem as #11. That one isn't only about link fields but also path fields, but sounds very similar to me. What do you think about it?

**Comment by robertgarrigos** [comment]
We can close this one, but it's not the same as #11. I'll answer you there.
