### ISSUE TITLE
No json is shown for views without pagination

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/headless#20]
My last PR introduced a bug when you try to show a view without pagination.

**Comment by robertgarrigos** [comment]
PR to fix it: https://github.com/backdrop-contrib/headless/pull/22

**Comment by robertgarrigos** [comment]
PR https://github.com/backdrop-contrib/headless/pull/24 also includes this

**Comment by serundeputy** [comment]
thanks i've merged https://github.com/backdrop-contrib/headless/pull/24
nice bug fix plus term ref data! :shipit:
