### ISSUE TITLE
term reference fields only show tid on node type json

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/headless#23]
One problem I'm having is that whenever I want to show a full node which contains a term reference field, the json for that field only contains the tid. It would be much useful to have the term name. I know that there is a term end point, but it's useless in this case as it needs the vocabulary name, which doesn't come either with the node json.

I will file a PR for a new v2/node end point which solves this.

**Comment by robertgarrigos** [comment]
PR: https://github.com/backdrop-contrib/headless/pull/24

**Comment by serundeputy** [comment]
nice addition; merged https://github.com/backdrop-contrib/headless/pull/24
