### ISSUE TITLE
feature request - work with Views

### ISSUE THREAD

**Issue by kevcol** [backdrop-contrib/headless#3]
First, thanks for this module, which works well out of the box.

Would you consider adding Views support?  

The use-case on my mind:
I'd like to have my iOS app query Backdrop for nodes created or updated since the last time the app was opened.  So I'd only create/update content not already cached in the app. I was thinking a simple View filtered by the Updated timestamp would do nicely, if I could output in JSON.

**Comment by serundeputy** [comment]
Hi @kevcol 

> Would you consider adding Views support?

Yes!  adding views support sounds like a great idea.

I have no roadmap for this yet though, but am open to the idea.  Are you up for making a roadmap/spec and/or PR?

thanks,
~Geoff

**Comment by serundeputy** [comment]
@kevcol added views support dd4c3eb9523ff5b5daadc2f9c087134b4483360f
