### ISSUE TITLE
Deliver views json w/ pager data.

### ISSUE THREAD

**Issue by serundeputy** [backdrop-contrib/headless#4]
I would like the json endpoints for paginated views to deliver the pager info as well as the views data.

* number of pages
* number of total results
* current page

**Comment by robertgarrigos** [comment]
I would also!! ;-) BTW, this is a gem of a module.... :-)

**Comment by robertgarrigos** [comment]
Added a PR for this: https://github.com/backdrop-contrib/headless/pull/13

**Comment by serundeputy** [comment]
@robertgarrigos this looks amazing; I can't wait to try it out! :robot: :rocket:

**Comment by serundeputy** [comment]
not backwards compatible; maybe we could release a `2.x` version and add `api/v2/%` to all the routes leaving the `1.x` version of the module for folks that are not ready for the breaking change?

And as you said call out this fact in the README.md

**Comment by robertgarrigos** [comment]
added the README changes to the PR

**Comment by robertgarrigos** [comment]
will do the `api/v2` change and the README accordingly.

**Comment by robertgarrigos** [comment]
Refactored

**Comment by serundeputy** [comment]
@robertgarrigos this is really great! Thanks for all your research, work, and refactors!

Merged into `1.x` will ship w/ `tag/1.x-1.3.0`
