### ISSUE TITLE
Is argument type for paragraphs really needed?

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/headless#43]
I'm updating the Laravel package (https://github.com/robertgarrigos/backdrop-headless-client - to Laravel 7) to pull from this headless module and found something I really don't like: paragraphs end points need a type argument for the paragraph (/api/v2/paragraphs/{type}/{id}). It is used only to check whether it has been enabled in the headless config or not, but the problem is that, in fact, it is not necessary to pull the paragraph from ddbb and, what's worst, there is no way, from a Laravel point of view, to know what is the type of the paragraph: once in Laravel, you pull a node data, which contains the paragraphs field with and id but no type.

I would take the type out from the endpoint, as we can pull it anyway from the entity and still do the check with config. Something like this:

```
/**
 * Page callback for paragraph types v2.
 */
function headless_paragraphs_item_v2($entity_id) {

  $config = config_get('headless.settings', 'paragraphs');

  $p = paragraphs_item_load($entity_id);

  if ($config[$p->bundle] != 1) {
    $json_error = ['code' => 404];
    backdrop_json_output($json_error);
    backdrop_exit();
  }

  $result = $p->view();
  backdrop_json_output($result);
  backdrop_exit();
}
```

Of course, the menu item should be fixed also:

```
$items['api/v2/paragraphs/%'] = array(
      'page callback' => 'headless_paragraphs_item_v2',
      'access callback' => TRUE,
      'page arguments' => array(3),
    );
```
No, the question is: how should we do it to keep backwards compatibility? Add a v3 end point??

**Comment by serundeputy** [comment]
I think `v3` is the only way I can think of to preserve backward compatibility.

should we make `v1`, `v2`, and `v3` directories to separate out the different behaviours from the `headless.module` file?

Should/can `v2` and `v3` endpoints that are not defined default to their `v1` or `v2` predecessors?

I don't know the answers to these questions and if the easiest/necessary thing is to add this `v3` for paragraphs i'm fine with that.

If the other questions have any merit we could split them out into new/follow up issues.

**Comment by robertgarrigos** [comment]
ok. let's add the v3 end points on their own directories, then. I will file a PR or several.
