### ISSUE TITLE
README references wrong build status

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/headless#51]
As we did the travisCI integration simultaneously, you accidentally added the wrong build status - now headless references the i18n status in the README.md. :wink:

https://raw.githubusercontent.com/backdrop-contrib/headless/1.x-1.x/README.md

**Comment by serundeputy** [comment]
doh: fixed: https://github.com/backdrop-contrib/headless/blob/1.x-1.x/README.md
