### ISSUE TITLE
The settings page needs some UX love

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/headless#9]
PR: https://github.com/backdrop-contrib/headless/pull/10

- Wraps user-exposed strings in `t()` (help text, fieldset labels)
- Instead of their machine names, uses human-readable labels for the checkboxes for content types, vocabularies, and paragraph types
- Change references of "node types" to "content types"
- Some defensive coding for cases where content types, paragraph types, or taxonomy vocabularies have not been created yet (minimal profile - or default, OOTB thingies have been deleted/disabled). In such cases, the respective fieldset gets expanded by default, and a "No [thingy] defined yet" message is shown in place of the checkboxes.
- Also checks if required modules are enabled (views_ui for example), and then also adds a "Manage [thingy]" link to point to the respective listing page, where people can add content/paragraph types, views, or vocabularies.

**Comment by klonos** [comment]
Before:

<img width="616" alt="screen shot 2019-02-19 at 7 04 30 am" src="https://user-images.githubusercontent.com/2423362/52974297-21f25d00-3415-11e9-9829-6583074c14d3.png">

After:

<img width="632" alt="screen shot 2019-02-19 at 7 03 10 am" src="https://user-images.githubusercontent.com/2423362/52974299-2454b700-3415-11e9-9fba-a563f591c00c.png">

**Comment by serundeputy** [comment]
Thanks @klonos Overall looks great!

I have some concerns about:

>Instead of their machine names, uses human-readable labels for the checkboxes for content types, vocabularies, and paragraph types

The api to serve these endpoints are for example `/api/node/{machine_name_of_type}`; so it is useful to know the machine name. Maybe we should display the nice name next to the checkbox as you have done and in parens `(machine_name: page)` or whatever the machine name is. Or maybe we should inform them here that the endpoint for thingy is `/api/{type}/{bundle}/{nid}`, so for `page` would be `/api/node/page/{nid}`?

We should do the same thing for views.  

> Change references of "node types" to "content types"

The api refers to these as nodes as does backdrop itself; so I flat out disagree with this change.

**Comment by robertgarrigos** [comment]
Agree on this. I was about to to do so in my fork. I'll file a PR.

**Comment by robertgarrigos** [comment]
Finally (bloody travis...) got the [PR](https://github.com/backdrop-contrib/headless/pull/31) ready

**Comment by serundeputy** [comment]
thanks @klonos and @robertgarrigos settings page looks great now!
